name: k6 test

on:
  workflow_dispatch:
    inputs:
        api:
          type: choice
          description: make choice endpoint
          options:
          - GET auth/token
          - POST connect/
          - POST external/
#         method:
#           description: 'method'
#           default: ''
#           required: true
#           type: string
        vus: 
          description: 'vus'
          default: ''
          required: false
          type: string
        duration: 
          description: 'duration'
          default: ''
          required: false
          type: string
        rps: 
          description: 'rps'
          default: ''
          required: false
          type: string
        parallelism: 
          description: 'parallelism'
          default: ''
          required: false
          type: string
#         template:
#           description: 'template'
#           default: ''
#           required: true
#           type: string
          
jobs:
  k6:
    name: k6
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Script
      run: |
        mkdir ~/.kube
        touch $HOME/.kube/config
        echo "Hello World" > $HOME/.kube/config
        cat $HOME/.kube/config
        data=$(cat $HOME/.kube/config | openssl enc -e -base64)
        
        echo "kubeconfig_data=${data}" >> $GITHUB_ENV

    - name: Create CRD
      uses: ymktmk/operate-k6-crd@main
      with:
        method: create
        vus: 1
        duration: 100
        parallelism: 1
        template: ./example/k6.yaml
        
    - name: Ls
      run: |
        pwd
        ls -la
        
