name: slack

on: 
  workflow_dispatch:
  
jobs:
  slack:
    name: slack
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Send Slack
      uses: ymktmk/slack-github-action@fix-setoutput
      with:
        channel-id: C04CR5WMSU8
        payload: |
         { "text": "aaa" }
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_TOKEN }}    
